version: "2"
volumes:
 db_data: {}
 wallet_build: {}

services:
 cli-wallet:
  build: cli-wallet
  ports:
   - 8092
   - 8099
  volumes:
   - ./cli-wallet/data:/conf/cli-wallet

 web-wallet:
  build: web-wallet
  ports:
   - "8080:80"
  volumes:
   - wallet_build:/bitshares-ui/build/dist

